# Generated by Django 5.2 on 2025-05-04 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Муж'), ('W', 'Жен')], max_length=20, verbose_name='Пол')),
                ('birth', models.DateField(help_text='xx.xx.xxxx', verbose_name='Дата рождения')),
                ('death', models.DateField(blank=True, help_text='xx.xx.xxxx', null=True, verbose_name='Дата смерти')),
                ('image', models.ImageField(default='photo/default_person_photo/default.png', upload_to='photo/upload_photo/', verbose_name='Фото')),
                ('place_of_birth', models.TextField(blank=True, help_text='Россия, Пермский Край, Пермь ...', verbose_name='Место рождения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='DApp.person', verbose_name='Отец')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='DApp.person', verbose_name='Мать')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to='DApp.person', verbose_name='Cупруг')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
    ]
