# Generated by Django 5.2 on 2025-05-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DApp', '0002_alter_person_father_alter_person_mother_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='spouse',
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married_date', models.DateField(blank=True, null=True)),
                ('divorced', models.BooleanField(default=False)),
                ('divorce_date', models.DateField(blank=True, null=True)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_partner1', to='DApp.person')),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_partner2', to='DApp.person')),
            ],
        ),
    ]
