# Generated by Django 5.2 on 2025-05-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DApp', '0003_remove_person_spouse_marriage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriage',
            options={'verbose_name': 'Супруги', 'verbose_name_plural': 'Супругов'},
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='partner1',
        ),
        migrations.RemoveField(
            model_name='marriage',
            name='partner2',
        ),
        migrations.AddField(
            model_name='marriage',
            name='husband',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_partner1', to='DApp.person', verbose_name='Муж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marriage',
            name='wife',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_partner2', to='DApp.person', verbose_name='Жена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marriage',
            name='divorce_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата развода'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='divorced',
            field=models.BooleanField(default=False, verbose_name='В разводе'),
        ),
        migrations.AlterField(
            model_name='marriage',
            name='married_date',
            field=models.DateField(blank=True, null=True, verbose_name='<Дата женитьбы'),
        ),
    ]
